fledge-iot/fledge-gui

- src/app/components/core/notifications/notification-service-modal/notification-service-modal.component.html
- src/app/components/core/notifications/notification-service-modal/notification-service-modal.component.ts
Signed-off-by: ashish-jabble <ashish@dianomic.com>
> FOGL-3559 foglamp reference fixes for service notification

- src/app/components/common/pagination/pagination.component.css
- src/app/components/common/pagination/pagination.component.html
- src/app/components/common/pagination/pagination.component.ts
- src/app/components/core/audit-log/audit-log.component.css
- src/app/components/core/audit-log/audit-log.component.html
- src/app/components/core/audit-log/audit-log.component.ts
- src/app/components/core/notifications/notification-log/notification-log.component.html
- src/app/components/core/notifications/notification-log/notification-log.component.ts
- src/app/components/core/packages-log/packages-log.component.html
- src/app/components/core/system-log/system-log.component.html
- src/app/components/core/system-log/system-log.component.ts
- src/app/components/core/system-log/system-log.module.ts
- src/app/pipes/search.pipe.ts
- src/app/services/audit.service.ts
- src/app/services/system-log.service.ts
- yarn.lock
**Syslog page (develop):**
**Syslog page (now):**
Auto-refresh and with 2 south services (sin1, sin2), 1 notification instance (Fl Notification1) and 1 North instance (PI)
Manual refresh
> [FOGL-3728]: GUI Improvements to log access

- README.md
- docs/changelog.md
> Changelog update for v1.8.0 release

- src/app/components/core/asset-readings/assets/assets.component.html
- src/app/components/core/backup-restore/backup-restore.component.html
- src/app/components/core/certificate/certificate-store/certificate-store.component.html
- src/app/components/core/configuration-manager/config-children/config-children.component.css
- src/app/components/core/north/add-task-wizard/add-task-wizard.component.html
- src/app/components/core/notifications/add-notification-wizard/add-notification-wizard.component.html
- src/app/components/core/packages-log/packages-log.component.html
- src/app/components/core/scheduler/list-schedules/list-schedules.component.html
- src/app/components/core/south/add-service-wizard/add-service-wizard.component.html
- src/app/components/core/south/south.component.css
- src/app/components/core/south/south.component.html
- src/app/components/core/support/support.component.html
- src/app/components/core/user-management/user-management.component.html
- src/app/components/layout/navbar/navbar.component.css
- src/app/components/layout/navbar/navbar.component.html
- src/styles.css
- yarn.lock
Below UI changes have been done:
> UI fixes (icons and text button)

- src/app/components/core/north/north-task-modal/north-task-modal.component.html
- src/app/components/core/system-log/system-log.component.ts
**DONE:**
[FOGL-4794](https://scaledb.atlassian.net/browse/FOGL-4794) has been updated for service info requirements
> [FOGL-4721.patch3]: Show service info and syslog for Northbound services

- src/app/components/core/configuration-manager/configuration-manager.component.css
- src/app/components/core/configuration-manager/configuration-manager.component.html
- src/app/components/core/scheduler/update-schedule/update-schedule.component.html
> [FOGL-4420.patch2]: DOM and css changes on Schedule and Configuration page

- src/app/components/core/north/north-task-modal/north-task-modal.component.html
Reference PR is [https://github.com/fledge-iot/fledge/pull/233](https://github.com/fledge-iot/fledge/pull/233)
> [FOGL-4794]: changed key management_port to managementPort in North service details

- src/app/components/core/settings/settings.component.css
- src/app/components/core/settings/settings.component.html
- src/app/components/core/settings/settings.component.ts
- src/app/components/layout/certificate-base-login/certificate-base-login.component.html
- src/app/components/layout/navbar/navbar.component.html
- src/app/components/layout/navbar/navbar.component.ts
- src/app/services/shared.service.ts
> [FOGL-3921_gui]: Show connection info on settings page and show version on hover fledge logo

- src/app/services/http.request.interceptor.ts
> [FOGL-4874]: Fixed issue when auth mandatory true and allow ping is false

- docs/changelog.md
> v1.8.2next  change-log update

- src/app/services/doc.service.ts
> removed lowercase from plugin name to fix broken doc link

- src/app/components/core/south/south.component.ts
> Fixed sorting on South page

- src/app/components/core/asset-readings/assets/assets.component.css
- src/app/components/core/asset-readings/assets/assets.component.html
- src/app/components/core/asset-readings/assets/assets.component.ts
- src/app/components/core/dashboard/dashboard.component.css
- src/app/components/core/dashboard/dashboard.component.html
- src/app/components/core/dashboard/dashboard.component.ts
- src/app/components/core/notifications/notification-service-modal/notification-service-modal.component.ts
- src/app/components/core/notifications/notifications.component.css
- src/app/components/core/notifications/notifications.component.html
- src/app/components/core/notifications/notifications.component.ts
- src/app/components/core/support/support.component.css
- src/app/components/core/support/support.component.html
- src/app/components/core/support/support.component.ts
- src/app/services/doc.service.ts
> FOGL-5097: Readthedocs Help links on various pages 

- src/app/components/core/asset-readings/readings-graph/readings-graph.component.ts
> nested reading object

- src/app/components/core/certificate/certificate-store/certificate-store.component.html
> FOGL-5402 simplify delete option in cert store. let API handled the configured certs and skipped login part

- src/app/components/core/user-management/user-profile/user-profile.component.ts
- src/app/services/user.service.ts
Test with https://github.com/fledge-iot/fledge/pull/398
> [FOGL-5483_gui]: Endpoints changes in GUI w.r.t. FOGL-5483

- src/app/components/core/certificate/certificate-store/certificate-store.component.ts
- src/app/components/core/certificate/upload-certificate/upload-certificate.component.html
- src/app/components/core/certificate/upload-certificate/upload-certificate.component.ts
Allowed extensions from GUI ['cert', 'cer', 'crt', 'csr', 'crl', 'pem', 'json', 'p12', 'pfx','der'];
> FOGL-5480.gui: Allowed more cert extensions in certificate store

- src/app/components/core/filter/filter-alert/filter-alert.component.html
- src/app/components/core/north/north-task-modal/north-task-modal.component.ts
- src/app/components/core/south/south-service-modal/south-service-modal.component.ts
> FOGL-5523: Fixed API calls on save when filter/applications deleted & discarded by add operation (re-added)

- docs/changelog.md
- src/app/components/common/file-upload-modal/file-upload-modal.component.css
- src/app/components/common/file-upload-modal/file-upload-modal.component.html
- src/app/components/common/file-upload-modal/file-upload-modal.component.spec.ts
- src/app/components/common/file-upload-modal/file-upload-modal.component.ts
- src/app/components/core/backup-restore/backup-restore.component.css
- src/app/components/core/backup-restore/backup-restore.component.html
- src/app/components/core/backup-restore/backup-restore.component.ts
- src/app/components/core/backup-restore/backup-restore.module.ts
- src/app/services/backup-restore.service.ts
- src/app/services/progress-bar.service.ts
JIRA logged for api improvements 
https://scaledb.atlassian.net/browse/FOGL-5913
> FOGL-5872: backup upload support

- src/app/components/core/notifications/add-notification-wizard/add-notification-wizard.component.css
- src/app/components/core/notifications/add-notification-wizard/add-notification-wizard.component.html
- src/app/components/core/notifications/add-notification-wizard/add-notification-wizard.component.ts
> FOGL-6069: Added doc link for notification type

- src/app/components/core/control-dispatcher/add-control-script/add-step/add-step.component.ts
> FOGL-6303: script save button enable/disable issue fix for write step selection 

- src/app/services/doc.service.ts
Signed-off-by: ashish-jabble <ashish@dianomic.com>
As per new changes in Core-doc https://github.com/fledge-iot/fledge/pull/721
> FOGL-6590 Notification URL updated as per new restructuring of services documentation

- src/app/app.component.ts
- src/app/app.module.ts
- src/app/components/core/settings/settings.component.ts
- src/app/components/layout/login/login.component.html
- src/app/components/layout/login/login.component.ts
- src/app/components/layout/navbar/navbar.component.ts
- src/app/services/auth.service.ts
- src/app/services/http.request.interceptor.ts
- src/app/services/shared.service.ts
- src/app/services/storage.service.ts
To test this PR 
* FogLAMP Manage GUI and foglamp-gui should be installed on same machine.
> FOGL-6812:  parameterise URL support to Fledge-GUI for token auth and connection setting

- src/app/components/core/user-management/create-user/create-user.component.html
- src/app/components/core/user-management/create-user/create-user.component.ts
- src/app/components/core/user-management/update-user/update-user.component.css
- src/app/components/core/user-management/update-user/update-user.component.html
- src/app/components/core/user-management/update-user/update-user.component.ts
- src/app/components/core/user-management/user-management.component.html
- src/app/components/core/user-management/user-management.component.ts
- src/app/components/core/user-management/user-profile/user-profile.component.ts
- src/app/services/roles.service.ts
Role name mapping in GUI
admin => Administrator, 
user => Editor,
view => Viewer, 
data_view => Data Viewer
> Role view mapping on  user profile and user management page for admin user

- src/app/components/core/configuration-manager/configuration-group/configuration-group.component.html
- src/app/components/core/configuration-manager/configuration-group/configuration-group.component.ts
- src/app/components/core/configuration-manager/configuration-manager.component.html
- src/app/components/core/configuration-manager/configuration-manager.component.ts
- src/app/components/core/configuration-manager/show-configuration/show-configuration.component.ts
- src/app/components/core/filter/add-filter-wizard/add-filter-wizard.component.html
- src/app/components/core/filter/add-filter-wizard/add-filter-wizard.component.ts
- src/app/components/core/north/add-task-wizard/add-task-wizard.component.html
- src/app/components/core/north/add-task-wizard/add-task-wizard.component.ts
- src/app/components/core/notifications/add-notification-wizard/add-notification-wizard.component.ts
- src/app/components/core/south/add-service-wizard/add-service-wizard.component.html
- src/app/components/core/south/add-service-wizard/add-service-wizard.component.ts
- src/app/directives/custom-validator.ts
- src/app/services/configuration-control.service.ts
Fixed Issues
1. [FOGL-7457](https://scaledb.atlassian.net/browse/FOGL-7457)
2. [FOGL-7458](https://scaledb.atlassian.net/browse/FOGL-7458)
3. [FOGL-7477](https://scaledb.atlassian.net/browse/FOGL-7477)
4. [FOGL-7470](https://scaledb.atlassian.net/browse/FOGL-7470)
5. JSON format issue 
6. validity expression checks
> FOGL-7457: Fixed configuration issues

- README.md
- docs/changelog.md
> change-log update

- angular.json
- docs/developers-guide.md
- package.json
- src/app/components/core/north/north-task-modal/north-task-modal.component.ts
- src/app/components/core/south/south-service-modal/south-service-modal.component.ts
- src/app/services/index.ts
- src/app/services/response-handler.service.ts
- src/app/services/toast.service.ts
- yarn.lock
**NOTE:**  Added open source library for alert messages handling [bulma-toast](https://github.com/rfoel/bulma-toast). Plan is to deprecate alert-component in favour of bulma-toast.
> FOGL-7510: Fixed error handling issue for forkJoin on north & south modal window

- src/app/components/common/time-dropdown/time-dropdown.component.css
- src/app/components/common/time-dropdown/time-dropdown.component.html
- src/app/components/common/time-dropdown/time-dropdown.component.ts
- src/app/components/core/asset-readings/readings-graph/readings-graph.component.css
- src/app/components/core/asset-readings/readings-graph/readings-graph.component.html
- src/app/components/core/asset-readings/readings-graph/readings-graph.component.ts
- src/app/components/core/settings/settings.component.css
- src/app/components/core/settings/settings.component.html
- src/app/components/core/settings/settings.component.ts
- src/app/directives/directives.module.ts
- src/app/directives/integer-only.directive.ts
1. Separate out time value from unit on readings graph page (Done).
2. Separate out time value from unit on settings page (Done).
3. Add help text for currently rendered graph (Done).
> FOGL-7692: Add granularity in time duration of readings graph

- src/app/components/core/control-dispatcher/add-control-script/add-step/add-step.component.ts
- src/app/components/core/control-dispatcher/pipelines/add-pipeline/add-control-pipeline.component.html
- src/app/components/core/control-dispatcher/pipelines/add-pipeline/add-control-pipeline.component.ts
- src/app/components/core/filter/add-filter-wizard/add-filter-wizard.component.ts
- src/app/components/core/filter/filter-list/filter-list.component.ts
- src/app/components/core/north/north-task-modal/north-task-modal.component.ts
- src/app/services/configuration-control.service.ts
1. Fixed  wrong filter category update  issue for control pipeline
2. Fixed undefined step control issue on control script
3. other code improvements related to filter pipeline order change.
4. Extra code removal from Add control pipeline component
> Fixed undefined step control issue on control script

- src/app/components/core/filter/filter-list/filter-list.component.css
- src/app/components/core/filter/filter-list/filter-list.component.html
- src/app/components/core/logs/audit-log/audit-log.component.css
- src/app/components/core/logs/notification-log/notification-log.component.css
- src/app/components/core/logs/packages-log/packages-log.component.css
- src/app/components/core/logs/system-log/system-log.component.css
- src/app/components/core/logs/system-log/system-log.component.html
- src/app/components/core/logs/tasks/tasks.component.css
- src/app/components/core/north/north-task-modal/north-task-modal.component.html
- src/app/components/core/notifications/notification-modal/notification-modal.component.html
- src/app/components/core/south/south-service-modal/south-service-modal.component.html
- src/app/components/core/user-management/create-user/create-user.component.ts
- src/app/components/core/user-management/user-management.component.html
- src/app/components/core/user-management/user-management.component.ts
- src/app/components/layout/side-menu/side-menu.component.html
- src/styles.css
> Issues fixed for GUI improvement

- src/app/components/core/backup-restore/backup-restore.component.html
- src/app/components/core/north/add-task-wizard/add-task-wizard.component.css
- src/app/components/core/north/add-task-wizard/add-task-wizard.component.html
- src/app/components/core/north/north-task-modal/north-task-modal.component.css
- src/app/components/core/north/north-task-modal/north-task-modal.component.html
- src/app/components/core/notifications/notification-modal/notification-modal.component.css
- src/app/components/core/notifications/notification-modal/notification-modal.component.html
- src/app/components/core/notifications/notification-service-modal/notification-service-modal.component.css
- src/app/components/core/notifications/notification-service-modal/notification-service-modal.component.html
- src/app/components/core/south/add-service-wizard/add-service-wizard.component.css
- src/app/components/core/south/add-service-wizard/add-service-wizard.component.html
- src/app/components/core/south/south-service-modal/south-service-modal.component.css
- src/app/components/core/south/south-service-modal/south-service-modal.component.html
- src/styles.css
> css changes in North, South and Notification modals and hover effect for bootstrap icons

- .gitignore
- angular.json
- e2e/run
- e2e/specs/app.e2e-common.ts
- e2e/specs/app.e2e-south.ts
- package.json
To run e2e tests in a specific browser, need to pass `--browser {browsername}` flag with `yarn e2e` command
> e2e test suites customized to work with fledge backend running on different machine

- src/app/components/core/scheduler/list-schedules/list-schedules.component.html
- src/app/components/core/scheduler/list-schedules/list-schedules.component.ts
- src/app/components/core/scheduler/schedule.ts
- src/app/components/core/scheduler/scheduler.module.ts
- src/app/components/core/scheduler/update-schedule/schedule-type.resolver.ts
- src/app/components/core/scheduler/update-schedule/update-schedule.component.css
- src/app/components/core/scheduler/update-schedule/update-schedule.component.html
- src/app/components/core/scheduler/update-schedule/update-schedule.component.ts
- src/app/services/schedules.service.ts
- src/app/utils.ts
Startup schedule can't be renamed & changed to other type.
> FOGL-8134: Manage Schedule update based on schedule type

- src/app/components/core/configuration-manager/bucket-configuration/bucket-configuration.component.ts
- src/app/services/configuration-control.service.ts
Test with https://github.com/fledge-iot/fledge/pull/1252
> FOGL-8355: Update UI to use bucket properties as an object

- src/app/components/common/node-editor/custom-node/custom-node.component.css
- src/app/components/common/node-editor/custom-node/custom-node.component.html
- src/app/components/common/node-editor/custom-node/custom-node.component.ts
- src/app/components/common/node-editor/filter.ts
- src/app/components/common/node-editor/node-editor.component.css
- src/app/components/common/node-editor/node-editor.component.html
- src/app/components/common/node-editor/node-editor.component.ts
- src/app/components/common/node-editor/south.ts
- src/app/components/common/node-editor/storage.ts
- src/app/components/core/configuration-manager/configuration-group/configuration-group.component.css
- src/app/components/core/configuration-manager/configuration-group/configuration-group.component.html
- src/app/components/core/configuration-manager/configuration-group/configuration-group.component.ts
- src/app/components/core/logs/system-log/system-log.component.css
- src/app/components/core/logs/system-log/system-log.component.html
- src/styles.css
- Hover effect removed from funnel icon on filter node
- Health icon removed if status of service is empty
- Name passed in delete confirmation dialog box for service and filter
- Breadcrumb font size changed in quickview
- Enable checkbox removed from filter config in quickview
- Sizing classes added for bi icons
> CSS related changes for flow editor

- e2e/run
e2e job passing http://jenkins.dianomic.com:8080/job/fledge_nightly_gui_e2e/1389/console
> FOGL-8555: Fixed e2e test build compilation issue

- src/app/components/core/system-alert/system-alert.component.css
- src/app/components/core/system-alert/system-alert.component.html
- src/app/components/core/system-alert/system-alert.component.ts
- src/app/components/layout/navbar/navbar.component.html
> FOGL-8306: Alerts stuff (patch2)

- src/app/components/core/system-alert/system-alert.component.ts
Required to sync with https://github.com/fledge-iot/fledge/pull/1325 changes.
> FOGL-8579_GUI: Updation as per backend changes

- src/app/components/common/node-editor/custom-node/custom-node.component.css
- src/app/components/common/node-editor/custom-node/custom-node.component.html
- src/app/components/common/node-editor/custom-notification-node/custom-notification-node.component.css
- src/app/components/common/node-editor/custom-notification-node/custom-notification-node.component.html
- src/app/components/common/node-editor/custom-notification-node/custom-notification-node.component.ts
- src/app/components/common/node-editor/editor.ts
- src/app/components/common/node-editor/node-editor.component.html
- src/app/components/common/node-editor/node-editor.component.ts
- src/app/components/common/node-editor/nodes/add-notification.ts
- src/app/components/core/logs/notification-log/notification-log.component.ts
- src/app/pipes/search.pipe.ts
> FOGL-8825: Removed extra GET notifications API call on Notification page (Flow editor)

- src/app/components/common/node-editor/custom-node/custom-node.component.html
- src/app/components/common/node-editor/custom-node/custom-node.component.ts
- src/app/components/common/node-editor/custom-notification-node/custom-notification-node.component.html
- src/app/components/common/node-editor/custom-notification-node/custom-notification-node.component.ts
- src/app/components/common/node-editor/editor.ts
- src/app/components/common/node-editor/flow-editor.service.ts
- src/app/components/common/node-editor/node-editor.component.ts
Node dropdown will now open on click instead of hover.
> FOGL-8767: Fixed node dropdown appears behind other nodes

- src/app/components/common/node-editor/editor.ts
- src/app/components/common/node-editor/node-editor.component.css
To delete a connection, user can right click on the connection and delete it using the delete option context menu.
> FOGL-8694: added context menu with delete option for connection deletion

- src/app/components/common/node-editor/node-editor.component.ts
- src/app/components/core/configuration-manager/configuration-group/configuration-group.component.ts
- src/app/components/core/configuration-manager/show-configuration/show-configuration.component.html
- src/app/components/core/configuration-manager/show-configuration/show-configuration.component.ts
- src/app/directives/directives.module.ts
- src/app/directives/max-length.directive.ts
- src/app/services/configuration-control.service.ts
Length validation check for string type config items.
> FOGL-8905: Length validation on configuration item of string type

- src/app/components/core/configuration-manager/configuration-manager.component.css
- src/app/components/core/configuration-manager/static-configuration/static-configuration.component.html
- src/app/components/core/control-dispatcher/add-control-script/add-step/add-configure/add-configure.component.css
- src/styles.css
> Some css fixes

- src/app/components/common/alert/alert.component.html
- src/app/components/common/alert/alert.component.ts
- src/app/components/common/node-editor/connector.ts
- src/app/components/common/node-editor/custom-node/custom-node.component.css
- src/app/components/common/node-editor/custom-node/custom-node.component.html
- src/app/components/common/node-editor/custom-node/custom-node.component.ts
- src/app/components/common/node-editor/custom-socket/custom-socket.component.ts
- src/app/components/common/node-editor/drop-plugin.ts
- src/app/components/common/node-editor/drop-stratgey.ts
- src/app/components/common/node-editor/editor.ts
- src/app/components/common/node-editor/filter.ts
- src/app/components/common/node-editor/flow-editor.service.ts
- src/app/components/common/node-editor/insert-node/index.ts
- src/app/components/common/node-editor/node-editor.component.html
- src/app/components/common/node-editor/node-editor.component.ts
- src/app/services/alert.service.ts
1. Removed node connection socket in the dock menu node 
2. Show (+) icon on the filter node when added in the connection 
3. When one add filter placeholder node dropped on the canvas, user is not allowed to drop any other. 
4. Filter Label size increased in the dock menu.
> FOFL-8986: Filter node change in dock menu 

- src/app/components/core/filter/add-filter-wizard/add-filter-wizard.component.css
- src/app/components/core/filter/add-filter-wizard/add-filter-wizard.component.html
- src/app/components/core/filter/add-filter-wizard/add-filter-wizard.component.ts
- src/app/components/core/north/add-task-wizard/add-task-wizard.component.css
- src/app/components/core/north/add-task-wizard/add-task-wizard.component.html
- src/app/components/core/notifications/add-notification-wizard/add-notification-wizard.component.css
- src/app/components/core/notifications/add-notification-wizard/add-notification-wizard.component.html
- src/app/components/core/plugin-modal/plugin-modal.component.css
- src/app/components/core/plugin-modal/plugin-modal.component.html
- src/app/components/core/south/add-service-wizard/add-service-wizard.component.css
- src/app/components/core/south/add-service-wizard/add-service-wizard.component.html
- src/app/components/core/south/add-service-wizard/add-service-wizard.component.ts
- src/styles.css
> FOGL-9472: UI enhancements in Add wizards 

- src/app/components/common/node-editor/flow-editor.service.ts
- src/app/components/core/configuration-manager/configuration-group/configuration-group.component.css
- src/app/components/core/notifications/notification-modal/notification-modal.component.html
- src/app/components/core/settings/settings.component.ts
Along with JIRA scope, handled below points also-
> FOGL-9512: Changes to make flow editor default view

- src/app/components/core/configuration-manager/kv-list-type-configuration/kv-list-type-configuration.component.css
- src/app/components/core/configuration-manager/kv-list-type-configuration/kv-list-type-configuration.component.html
- src/app/components/core/configuration-manager/kv-list-type-configuration/kv-list-type-configuration.component.ts
- src/app/components/core/configuration-manager/kvlist-card/kvlist-card.component.html
- src/app/components/core/configuration-manager/kvlist-card/kvlist-card.component.ts
- src/app/components/core/configuration-manager/list-card/list-card.component.html
- src/app/components/core/configuration-manager/list-card/list-card.component.ts
- src/app/components/core/configuration-manager/list-table/list-table.component.css
- src/app/components/core/configuration-manager/list-table/list-table.component.html
- src/app/components/core/configuration-manager/list-table/list-table.component.ts
- src/app/components/core/configuration-manager/list-type-configuration/list-type-configuration.component.css
- src/app/components/core/configuration-manager/list-type-configuration/list-type-configuration.component.html
- src/app/components/core/configuration-manager/list-type-configuration/list-type-configuration.component.ts
- src/app/components/core/configuration-manager/toggle-switch/toggle-switch.component.html
- src/app/components/core/configuration-manager/toggle-switch/toggle-switch.component.ts
- src/styles.css
-  Export file name : ServiceName-configKey.(ext) This is already working fine.
> FOGL-9270-patch: Enhancements in grid view and detail view for list & kvlist
